Business problem - predict the price of banglore house 

In [125]:
import pandas as pd 

In [126]:
path = r"https://drive.google.com/uc?export=download&id=1xxDtrZKfuWQfl-6KA9XEd_eatitNPnkB"
df = pd.read_csv(path)
df.head()

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3.0,2.0,150.0,1672.0,3,8971.291866,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,3.0,3.0,149.0,1750.0,3,8514.285714,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3.0,2.0,150.0,1750.0,3,8571.428571,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2.0,2.0,40.0,1250.0,2,3200.000000,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2.0,2.0,83.0,1200.0,2,6916.666667,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0


## Split DATA


In [127]:
x = df.drop('price' , axis=1)
y = df['price']

print('shape of  x = ',x.shape)
print('shape of  y = ',y.shape)


shape of  x =  (7120, 107)
shape of  y =  (7120,)


In [128]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test ,y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=51)
print("shape of x_train=" , x_train.shape)
print("shape of x_test" , x_test.shape)
print("shape of y_train" , y_train.shape)
print("shape of y_test" , y_test.shape)

shape of x_train= (5696, 107)
shape of x_test (1424, 107)
shape of y_train (5696,)
shape of y_test (1424,)


# Feature scaling 

In [130]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x_train)
x_train  = sc.transform(x_train)
x_test = sc.transform(x_test)

# Polynomial Linear Regression -ML Model Traning

In [131]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [132]:
poly_reg = PolynomialFeatures(degree=2 )
poly_reg.fit(x_train)
x_train_poly = poly_reg.transform(x_train)
x_test_poly =poly_reg.transform(x_test)

In [133]:
x_train_poly.shape,x_test_poly.shape

((5696, 5886), (1424, 5886))

In [134]:
lr = LinearRegression()


lr.fit(x_train_poly,y_train)

LinearRegression()

In [135]:
lr.score(x_test_poly, y_test,)

1.0

In [136]:
lr.predict([x_test_poly[0,:]])



array([80.])

In [137]:
y_predict = lr.predict(x_test_poly)
y_predict

array([ 80.,  40., 120., ...,  32.,  63., 180.])

In [138]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [139]:
from sklearn.metrics import mean_squared_error
import numpy as np
mse = mean_squared_error(y_test,y_predict)
rmse = np.sqrt(mse)

mse , rmse

(2.1130074877336933e-23, np.float64(4.596746118433879e-12))

## Linear Regression -- ML Model Traning 

In [140]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()


lr.fit(x_train, y_train)   ## x , y ko learn krga

LinearRegression()

In [141]:
lr.coef_  ## model n kiya kiya lrarn kiya 

array([-5.70206143e+00, -1.25679916e+00,  8.27341833e+01, -1.44906911e+01,
        5.75662723e+01,  1.88468905e-01, -1.72593897e+00, -4.51058311e+00,
       -2.22589244e+00, -4.28978455e+00, -2.44590976e+00,  5.40246226e-01,
       -1.03633400e+00,  1.43064873e+00, -6.25029424e-02, -1.51548783e+00,
       -2.14422789e-01,  2.16244155e+00, -1.48710228e+00,  1.95250816e+00,
       -3.10761125e+00, -1.28138668e+00, -1.01367155e+00,  1.37968545e-02,
        1.10383858e+00,  1.26497611e+00, -3.52405517e+00, -1.21398741e+00,
       -5.04622019e-01,  1.46299181e+00, -5.50064233e-01, -8.46468162e-02,
        6.84882188e-01, -1.39849820e+00, -1.94761710e-02, -1.57716300e+00,
        4.20886278e-01,  8.03443207e-01,  2.99182164e+00,  3.86430413e-03,
        1.05037261e-01,  2.89115612e-01, -3.16916626e-01,  1.05625868e+00,
       -1.39649279e+00, -3.10533604e+00,  1.01764011e-01, -7.49672917e-02,
       -8.03271555e-01, -1.27061856e+00, -8.54046164e-01,  2.64566484e-01,
        9.10688839e-01, -

In [142]:
lr.intercept_   ## B0 ki value h constant value 

np.float64(95.08027299859552)

### Predict the og home and test

In [143]:
x_test[0,:]

array([ 0.71301986,  0.0112734 ,  0.30202307,  0.65677518, -0.48064341,
       -1.7385623 ,  2.11587407, -0.25430867,  0.51007548, -0.18373025,
       -0.16389438, -0.1473229 , -0.13023539, -0.12812824, -0.12598816,
       -0.12454231, -0.12953656, -0.12381344, -0.12010681, -0.11551113,
       -0.10992018, -0.10909925, -0.10660036, -0.11234866, -0.09315135,
       -0.08618799, -0.08923672, -0.09023078, -0.08721571, -0.09023078,
       -0.08721571, -0.08195215, -0.08195215, -0.07633675, -0.0751646 ,
       -0.08085949, -0.0739743 , -0.07975227, -0.07153563, -0.0751646 ,
       -0.0677166 , -0.08085949, -0.07153563, -0.07862985, -0.0751646 ,
       -0.07862985, -0.06504853, -0.0751646 , -0.06901264, -0.0751646 ,
       -0.06901264, -0.07028523, -0.07276497, -0.07028523, -0.06367332,
       -0.06226825, -0.06226825, -0.06639573, -0.06504853, -0.05935999,
       -0.06083125, -0.06639573, -0.06639573, -0.06226825, -0.06367332,
       -0.05935999, -0.06639573, -0.06367332, -0.06226825, -0.06

In [144]:
lr.predict([x_test[0,:]])

array([76.90661876])

In [145]:
lr.predict(x_test)

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [146]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [147]:
lr.score(x_test,y_test)  ## r^2

0.7903837092682251

## implement RIDGE and lassso Regration 

In [148]:
from sklearn.linear_model import Ridge, Lasso   ## ye tab use krte jab model overfit ho jay 

In [149]:
rd = Ridge()   ## alpha ki 0 bhi kr skte by default 1 hoti  h 

rd.fit(x_train,y_train)
rd.score(x_test,y_test)

0.7905686374336645

In [150]:
ls = Lasso()
ls.fit(x_train,y_train)
ls.score(x_test,y_test)


0.8036373003525776

In [151]:
rd2 = Ridge(alpha=2)   

rd2.fit(x_train,y_train)
rd2.score(x_test,y_test)

0.7907530260397955

In [152]:
ls2 = Lasso(alpha=2)
ls2.fit(x_train,y_train)
ls2.score(x_test,y_test)

0.8160181533703601

# Model evaluation

Root mean squar error

In [153]:
y_pred = lr.predict(x_test)
y_pred

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [154]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [155]:
from sklearn.metrics import mean_squared_error
import numpy as np


In [ ]:
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

print("mse=" , mse)
print('rsme= ', rmse)

mse= 4211.806905823332
rsme=  64.89843531105609


# R-square

In [157]:
from sklearn.metrics import r2_score

In [158]:
r2_score(y_test , y_pred)

0.7903837092682251