suppor  vector regression

In [15]:
import pandas as pd

In [16]:
path = "https://drive.google.com/uc?export=download&id=1xxDtrZKfuWQfl-6KA9XEd_eatitNPnkB"
df = pd.read_csv(path)

## Split data

In [17]:
x = df.drop('price' , axis=1)
y = df['price']

print('shape of  x = ',x.shape)
print('shape of  y = ',y.shape)


shape of  x =  (7120, 107)
shape of  y =  (7120,)


In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test ,y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=51)
print("shape of x_train=" , x_train.shape)
print("shape of x_test" , x_test.shape)
print("shape of y_train" , y_train.shape)
print("shape of y_test" , y_test.shape)

shape of x_train= (5696, 107)
shape of x_test (1424, 107)
shape of y_train (5696,)
shape of y_test (1424,)


# Feature scaling 

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x_train)
x_train  = sc.transform(x_train)
x_test = sc.transform(x_test)

# support vector regression -ML Model Traning

In [30]:
from sklearn.svm import SVR

In [21]:
svr_rbf = SVR(kernel='rbf')  

svr_rbf.fit(x_train,y_train)
svr_rbf.score(x_test,y_test)


0.2063803584082815

In [22]:
svr_linear = SVR(kernel='linear')  

svr_linear.fit(x_train,y_train)
svr_linear.score(x_test,y_test)


0.7962731302544066

In [23]:
svr_poly = SVR(kernel='poly',degree=2)  

svr_poly.fit(x_train,y_train)
svr_poly.score(x_test,y_test)


0.18266215211874637

# predict the value of Home and test 

In [24]:
x_test[0]

array([ 0.71301986,  0.0112734 ,  0.30202307,  0.65677518, -0.48064341,
       -1.7385623 ,  2.11587407, -0.25430867,  0.51007548, -0.18373025,
       -0.16389438, -0.1473229 , -0.13023539, -0.12812824, -0.12598816,
       -0.12454231, -0.12953656, -0.12381344, -0.12010681, -0.11551113,
       -0.10992018, -0.10909925, -0.10660036, -0.11234866, -0.09315135,
       -0.08618799, -0.08923672, -0.09023078, -0.08721571, -0.09023078,
       -0.08721571, -0.08195215, -0.08195215, -0.07633675, -0.0751646 ,
       -0.08085949, -0.0739743 , -0.07975227, -0.07153563, -0.0751646 ,
       -0.0677166 , -0.08085949, -0.07153563, -0.07862985, -0.0751646 ,
       -0.07862985, -0.06504853, -0.0751646 , -0.06901264, -0.0751646 ,
       -0.06901264, -0.07028523, -0.07276497, -0.07028523, -0.06367332,
       -0.06226825, -0.06226825, -0.06639573, -0.06504853, -0.05935999,
       -0.06083125, -0.06639573, -0.06639573, -0.06226825, -0.06367332,
       -0.05935999, -0.06639573, -0.06367332, -0.06226825, -0.06

In [25]:
svr_linear.predict([x_test[0]])


array([86.5369287])

In [26]:
y_pred = svr_linear.predict(x_test)
y_pred

array([ 86.5369287 ,  33.7040083 , 122.48338476, ...,  26.2396233 ,
        64.52654442, 176.17522132])

In [27]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [28]:
from sklearn.metrics import mean_squared_error
import numpy as np

mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

print("mse=" , mse)
print('rsme= ', rmse)

mse= 4093.4711414879107
rsme=  63.98024024249917
